[project]
name = 'simple-owner'
description = 'A simple owner dApp demonstrating basic Clarity smart contract ownership and transfer functionality'
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.owner]
path = 'contracts/owner.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false


