[project]
name = 'simple-toggle'
description = 'A simple toggle dApp demonstrating basic Clarity smart contract functionality'
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.toggle]
path = 'contracts/toggle.clar'
clarity_version = 4
epoch = 3.0

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false


