[project]
name = 'simple-ft'
description = 'A simple FT dApp demonstrating a basic fungible token in Clarity'
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.ft]
path = 'contracts/ft.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false


