[project]
name = 'simple-nft'
description = 'A simple NFT dApp demonstrating basic mint and transfer functionality in Clarity'
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.nft]
path = 'contracts/nft.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false


