[project]
name = 'simple-counter'
description = 'A simple counter dApp demonstrating basic Clarity smart contract functionality'
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false

